version: '3.1'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # app-pm2:
  #   container_name: app-pm2
  #   #构建容器
  #   build: .
  #   environment:
  #     - DB_HOST=mysql
  #     - DB_NAME=smarty
  #     - DB_USER=root
  #     - DB_PASSWORD=example
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql
    
    #直接从git拉去
    # build: git@github.com:su37josephxia/docker_ci.git#:backend
    # 需要链接本地代码时
    # volumes:
    #   - ./backend:/usr/src/app
